---
title: "Accessibility commitment"
#image: 
#image-alt: 
---
I am fairly new to web design and development, but I am committed to making my website as accessible as possible.


This accessibility commitment was adapted from [Jadey Ryan](www.jadeyryan.com) which modified it from [Silvia Canelón's commitment](https://silviacanelon.com/accessibility).

## Feedback

I welcome any feedback on the accessibility and inclusivity of my site and content. Please let me know if you encounter any accessibility barriers or areas for improvement and I'll do my best to incorporate them.

## Accessibility practices

This site has been designed with the following features in mind:

- A color palette that meets [WCAG 2.1 AA](https://www.w3.org/WAI/WCAG21/quickref/) standards for contrast.
- Alternative text for all informative images.
- Readable font faces, specifically to avoid impostor letter shapes and mirroring.
  - Each character in [iIl], [ceo], and [db qp] should all be distinct from one another.[^1] 
  - This site primarily uses `Domine` for headings, `Atkinson Hyperlegible` for body text (developed by the [Braille Institute](https://brailleinstitute.org/freefont)), and Fira Code for code.
- A table of contents in the sidebars for easier navigation.

[^1]: Added the [ceo] and [db qp] tests from Cara Thompson's amazing [data viz design system talk](https://www.cararthompson.com/talks/nhsr2023-dataviz-design-system/), specifically slide 22: Font inspiration.

## Accessibility tools

I use the following to best inform my accessibility practices:

-   [Google Lighthouse Tool](https://developer.chrome.com/docs/lighthouse/accessibility/)
-   [Google Chrome Accessibility Features Reference](https://developer.chrome.com/docs/devtools/accessibility/reference/)
-   [Colour Contrast Checker](https://colourcontrast.cc/)
-   [Viz Palette](https://projects.susielu.com/viz-palette)
- [WAVE Web Accessibility Evaluation Tool](https://wave.webaim.org/)
-   [Microsoft Edge Accessibility Guide](https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/accessibility/test-inspect-tool)